language: node_js
node_js:
 - 10
addons:
 - chrome: stable
before_script:
 - yarn global add @angular/cli
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
services:
  - mysql
sudo: required
dist: trusty
test:
  - mySQL
before_install:
  - mysql -e 'CREATE DATABASE mySQL;'
script:
  - npm run jest
  - ng test

