language: node_js
node_js:
 - 10
addons:
 - chrome: stable
before_script:
 - yarn global add @angular/cli
services:
  - mysql
test:
  - mySQL
before_install:
  - mysql -e 'CREATE DATABASE mySQL;'
script:
  - npm run jest
  - ng test

