language: node_js
node_js:
 - 10
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
services:
  - mysql
test:
  - mySQL
before_install:
  - mysql -e 'CREATE DATABASE mySQL;'
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli
install:
  - npm ci
script:
  - npm run jest

